# Utilise une image de base Node.js
FROM node:16

# Crée un répertoire pour l'application
WORKDIR /app

# Copie les fichiers de dépendances
COPY package.json package-lock.json ./

# Installe les dépendances
RUN npm install

# Copie le reste du code de l'application
COPY . .

# Expose le port sur lequel l'API écoute
EXPOSE 3000

# Commande pour démarrer l'application
CMD ["npm", "start"]